spring:
    application:
        name: liteflow-etcd

liteflow:
    rule-source-ext-data-map:
        endpoints: http://127.0.0.1:2379
        chainPath: /liteflow/chain
        scriptPath: /liteflow/script