spring:
    application:
        name: liteflow-etcd

liteflow:
    rule-source-ext-data-map:
        endpoints: http://182.254.246.42:2379
        chainPath: /liteflow/chain
        scriptPath: /liteflow/script