spring:
  application:
    name: liteflow-mysql

liteflow:
  rule-source-ext-data-map:
    url: jdbc:mysql://localhost:3306/poseidon
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    tableName: chain
    elDataField: el_data


